(function() {var implementors = {};
implementors["simd"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html' title='core::ops::Neg'>Neg</a> for <a class='struct' href='simd/struct.i32x4.html' title='simd::i32x4'>i32x4</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html' title='core::ops::Neg'>Neg</a> for <a class='struct' href='simd/struct.i16x8.html' title='simd::i16x8'>i16x8</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html' title='core::ops::Neg'>Neg</a> for <a class='struct' href='simd/struct.i8x16.html' title='simd::i8x16'>i8x16</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html' title='core::ops::Neg'>Neg</a> for <a class='struct' href='simd/struct.f32x4.html' title='simd::f32x4'>f32x4</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html' title='core::ops::Neg'>Neg</a> for <a class='struct' href='simd/x86/sse2/struct.i64x2.html' title='simd::x86::sse2::i64x2'>i64x2</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html' title='core::ops::Neg'>Neg</a> for <a class='struct' href='simd/x86/sse2/struct.f64x2.html' title='simd::x86::sse2::f64x2'>f64x2</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html' title='core::ops::Neg'>Neg</a> for <a class='struct' href='simd/x86/avx/struct.i64x4.html' title='simd::x86::avx::i64x4'>i64x4</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html' title='core::ops::Neg'>Neg</a> for <a class='struct' href='simd/x86/avx/struct.i32x8.html' title='simd::x86::avx::i32x8'>i32x8</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html' title='core::ops::Neg'>Neg</a> for <a class='struct' href='simd/x86/avx/struct.i16x16.html' title='simd::x86::avx::i16x16'>i16x16</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html' title='core::ops::Neg'>Neg</a> for <a class='struct' href='simd/x86/avx/struct.i8x32.html' title='simd::x86::avx::i8x32'>i8x32</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html' title='core::ops::Neg'>Neg</a> for <a class='struct' href='simd/x86/avx/struct.f64x4.html' title='simd::x86::avx::f64x4'>f64x4</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Neg.html' title='core::ops::Neg'>Neg</a> for <a class='struct' href='simd/x86/avx/struct.f32x8.html' title='simd::x86::avx::f32x8'>f32x8</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
